name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

      - name: Build Docker container
        run: |
          echo "Building Docker container..."
          docker build -t ${{ secrets.DOCKER_USERNAME }}/phishproj:latest .

      - name: Push Docker container to Docker Hub
        run: |
          echo "Pushing Docker container to Docker Hub..."
          docker push ${{ secrets.DOCKER_USERNAME }}/phishproj:latest
